# Generated by Django 6.0.4 on 2026-07-19 11:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builty', '0005_alter_builty_document_status'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('scheduled_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builty', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip', to='builty.builty')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-scheduled_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='trips.trip')),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'scheduled_date'], name='trips_trip_status_2dda6d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_trip_driver__692693_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'status'], name='trips_trip_vehicle_b6bc2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'in_transit'))), fields=('driver',), name='unique_active_trip_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'in_transit'))), fields=('vehicle',), name='unique_active_trip_per_vehicle'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['trip', 'expense_date'], name='trips_tripe_trip_id_558c77_idx'),
        ),
    ]
