# Generated by Django 6.0.4 on 2026-06-07 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builty',
            options={},
        ),
        migrations.RenameField(
            model_name='builty',
            old_name='total_freight',
            new_name='freight_amount',
        ),
        migrations.AddField(
            model_name='builty',
            name='builty_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='builty',
            name='dispatch_status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('transit', 'In Transit'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='builty',
            name='builty_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='goods_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='builty',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('topay', 'To Pay')], default='topay', max_length=10),
        ),
        migrations.AlterField(
            model_name='builty',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
