# Generated by Django 6.0.4 on 2026-06-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builty', '0002_alter_builty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='package_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
