# Generated by Django 6.0.4 on 2026-07-18 13:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builty', '0003_alter_builty_package_count'),
        ('customers', '0004_remove_customer_name_customer_cnic_ntn_and_more'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builty',
            options={'ordering': ('-builty_date', '-created_at')},
        ),
        migrations.AddField(
            model_name='builty',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='builty',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='document_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], db_index=True, default='finalized', max_length=15),
        ),
        migrations.AddField(
            model_name='builty',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builties', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='builty',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builties', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='builty',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='builty',
            name='builty_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='builty',
            name='builty_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='destination_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='builty',
            name='dispatch_status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('transit', 'In Transit'), ('completed', 'Completed')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='builty',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='builty',
            name='goods_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='builty',
            name='origin_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='builty',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='builty',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['document_status', 'dispatch_status'], name='builty_buil_documen_dc8c35_idx'),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['builty_date'], name='builty_buil_builty__11decd_idx'),
        ),
    ]
