# Generated by Django 6.0.4 on 2026-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builty', '0004_alter_builty_options_builty_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='document_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=15),
        ),
    ]
