# Generated by Django 6.0.4 on 2026-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_current_balance_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('walkin', 'Walk-In')], default='walkin', max_length=20),
        ),
    ]
