# Generated by Django 6.0.4 on 2026-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cnic', models.CharField(help_text='Format: 35202-1234567-1', max_length=15, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('driver_type', models.CharField(choices=[('company', 'Company Driver'), ('contract', 'Contract Driver'), ('external', 'External / Market Driver')], default='company', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(choices=[('htv', 'HTV'), ('ltv', 'LTV'), ('psv', 'PSV'), ('other', 'Other')], default='htv', max_length=20)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField()),
                ('license_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
