# Generated by Django 6.0.4 on 2026-07-18 10:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer'), ('mazda', 'Mazda'), ('pickup', 'Pickup'), ('dumper', 'Dumper'), ('tanker', 'Tanker'), ('other', 'Other')], default='truck', max_length=30)),
                ('body_type', models.CharField(choices=[('open', 'Open Body'), ('container', 'Container'), ('flatbed', 'Flatbed'), ('tanker', 'Tanker'), ('dumper', 'Dumper'), ('refrigerated', 'Refrigerated'), ('other', 'Other')], default='open', max_length=30)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ownership_type', models.CharField(choices=[('company_owned', 'Company Owned'), ('attached', 'Attached Vehicle'), ('market_hired', 'Market / Hired Vehicle')], default='company_owned', max_length=30)),
                ('owner_name', models.CharField(blank=True, help_text='Required for attached or market vehicles.', max_length=150, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('depreciation_start_date', models.DateField(blank=True, help_text='Date vehicle became available for company use.', null=True)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected resale value after useful life.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('useful_life_years', models.PositiveSmallIntegerField(default=10, help_text='Expected remaining useful life.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line')], default='straight_line', max_length=30)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('sold', 'Sold')], default='available', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
