# Generated by Django 6.0.4 on 2026-06-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='is_active',
        ),
    ]
