# Generated by Django 6.0.4 on 2026-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_transactioncategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='category_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('owner', 'Owner Transaction')], default='Temp', max_length=20),
            preserve_default=False,
        ),
    ]
