# Generated by Django 6.0.4 on 2026-07-01 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transactioncategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='cash_flow',
            field=models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], default='Cash', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
