# Generated by Django 6.0.4 on 2026-07-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transactioncategory_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
    ]
