# Generated by Django 6.0.4 on 2026-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='owner_action',
            field=models.CharField(blank=True, choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='cash_flow',
            field=models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], editable=False, max_length=10),
        ),
    ]
