# Generated by Django 6.0.4 on 2026-07-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_transaction_transaction_date'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trip_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transaction', to='trips.tripexpense'),
        ),
    ]
